---
- name: Get facts
  hosts: all
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  vars_prompt:
    - name: ADMUSER
      prompt: Username
      private: no
  tasks:
    - name: Run show commands
      junos_command:
        host: "{{ inventory_hostname }}"
        user: "{{ ADMUSER }}"
        commands: 
          - show version
      register: junos

