---
- name: Get facts
  hosts: all
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  vars_prompt:
    - name: ADMUSER
      prompt: Username
      private: no
  tasks:
    - name: Run show commands
      junos_install_os:
        host: "{{ inventory_hostname }}"
        user: "{{ ADMUSER }}"
        version: 15.1R6-S2.1
        package: /home/vagrant/virtualenv/junos/jinstall-ex-4200-15.1R6-S2.1-domestic-signed.tgz
        logfile: software.log
