#!/usr/bin/expect -f

# usage is: ./scriptname.sh <username> <switch IP> 

spawn ssh -l [lindex $argv 0] [lindex $argv 1]
expect ">"

send "edit\r"
expect "#"

send "set set interfaces interface-range security-ports ether-options link-mode full-duplex\r"
expect "#"

send "set interfaces interface-range security-ports ether-options speed 100m\r"
expect "#"

send "commit\r"
expect "commit complete"

send "exit\r"
expect ">"

send "exit\r"
expect "$"
